<p>
<table align="center" border="5" cellpadding="10">
<tr>
<td colspan="2"><a href="view_my_jobs.php?yearval=2010_11"><b>View list of my teaching duties (10/11)</b></a></td>
<td><a href="view_people.php?yearval=2010_11">View list of people<br>(10/11)</a></td>
<td><a href="view_jobs.php?yearval=2010_11">View list of jobs<br>(10/11)</a></td>
<td><a href="view_units.php?yearval=2010_11">View list of units<br>(10/11)</a></td>
<!--td><a href="view_points_formulae.php?yearval=2010_11">View list of points formulae for marking<br>(10/11)</a></td-->
<td><a href="view_faculty_summary.php?yearval=2010_11">View stint point summary<br>(10/11)</a></td>
<td><a href="view_timetable.php?yearval=2010_11">View timetable<br>(10/11)</a></td>
</tr>
<tr>
<td colspan="2"><a href="view_my_jobs.php?yearval=2009_10"><b>View list of my teaching duties (09/10)</b></a></td>
<td><a href="view_people.php?yearval=2009_10">View list of people<br>(09/10)</a></td>
<td><a href="view_jobs.php?yearval=2009_10">View list of jobs<br>(09/10)</a></td>
<td><a href="view_units.php?yearval=2009_10">View list of units<br>(09/10)</a></td>
<!--td><a href="view_points_formulae.php?yearval=2009_10">View list of points formulae for marking<br>(09/10)</a></td-->
<td><a href="view_faculty_summary.php?yearval=2009_10">View stint point summary<br>(09/10)</a></td>
<td><a href="view_timetable.php?yearval=2009_10">View timetable<br>(09/10)</a></td>
</tr>
</table>

<p> You are logged in as <?php echo $_SERVER['REMOTE_USER']; ?>.
</p>

<p>
Please do not use the "back" or "reload" buttons when using the teaching duties database.
</p>
</div>
