<!-- CUED header: milab-h.html -->
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<link rel="shortcut icon" href="/favicon.ico">

<link rel="stylesheet" type="text/css" href="styles/camstyle.css" />
<link rel="stylesheet" type="text/css" href="styles/cuedglobal.css" />
<link rel="stylesheet" type="text/css" href="styles/milab.css" />
<style type="text/css">
	.yeartext { font-size: 75%; font-weight: 400 }
	.deptitle { font-weight: 400; color: rgb(35,35,35) }
	.welcometext { margin: auto 2% auto 3% }
</style>
</head>
<body bgcolor="#ffffff" text="#000000" link="#003399" alink="#cc0000" vlink="#cc3333">

<table cellpadding="0" cellspacing="0" border="0" width="100%" summary="navigation bar">
<tr>
<td bgcolor="#0099cc" width="100%" class="null"><img src="images/pixel.gif" width="1" height="16" alt="" /></td>
</tr>

<tr>
<td bgcolor="#cccccc" class="null"><img src="images/pixel.gif" width="1" height="2" alt="" /></td>
</tr>
</table>

<table cellpadding="0" cellspacing="0" border="0" width="100%" summary="departmental header">
<tr>
<td><img src="images/uniban-s.gif" border="0" alt="University of Cambridge " /></td>
<td align="center" class="deptitle" valign="bottom"><?php global $description; echo "$description"; ?>&nbsp;<br>
<?php echo "$yeartext"; ?></td>
<td align="right" class="deptitle" valign="bottom"><?php global $department; echo "$department"; ?></td>


<td><a href="Documents/TODBUserGuide.htm" target="_blank">
<img src="images/QuestionMark.png" border="0" alt="Access Help Pages" title="Access Help Pages" align="right" />
</a></td>
</tr>

<tr>
<td bgcolor="#0099cc" colspan="4" class="null"><img src="images/pixel.gif" width="1" height="4" alt="" /></td>
</tr>

<tr>
<td bgcolor="#cccccc" colspan="4" class="null"><img src="images/pixel.gif" width="1" height="2" alt="" /></td>
</tr>
</table>

<!-- end CUED header -->

