<?php
?>

<script type="text/javascript">
<!--
function tick()
{
	var boxid=document.getElementsByName("jty_le");
	boxid.checked=true;
	document.getElementsByName("jty_le").checked=true;
}
//-->
</script>

<?php
//if ($js_select == "jobtype")  ?>


		<script type="text/javascript">
		<!--
		//
		document.write("<td><input type=\"Checkbox\" name=\"tick_all\" onclick=\"tick()\" />test1</td>");
		document.getElementsByName("jty_le").checked=true;
		//-->
		</script>
		


<?php ?>
